# Generated by Django 4.0.1 on 2022-01-21 15:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_category_options_news_comment_member'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='member',
            name='interest',
        ),
    ]
