# Generated by Django 4.0.1 on 2022-01-21 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_remove_member_interest'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='interest',
            field=models.ManyToManyField(blank=True, to='main.Category', verbose_name='interest'),
        ),
    ]
